[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
binrw = "0.15.0"
chrono = "0.4.42"
enum-as-inner = "0.6.1"
thiserror = "2.0.17"
url = "2.5.4"
uuid = "1.19.0"
xml-rs = "1.0.0"
