[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
binrw = "0.15.0"
chrono = "0.4.43"
enum-as-inner = "0.7.0"
thiserror = "2.0.18"
url = "2.5.8"
uuid = "1.20.0"
xml-rs = "1.0.0"
